[tool.poetry]
name = "dataclasses-struct"
version = "0.1.0"
description = ""
authors = ["Harry Mander <harrymander96@gmail.com>"]
# readme = "README.md"
packages = [{include = "dataclasses_struct"}]

[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.5.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
mypy = "^1.1.1"
pytest = "^7.2.2"

[tool.pytest.ini_options]
testpaths = ["test"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
