name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    strategy:
      matrix:
        pyversion: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["Ubuntu", "Windows", "macOS"]
        include:
          - os: Windows
            image: windows-latest
          - os: Ubuntu
            image: ubuntu-latest
          - os: macOS
            image: macos-latest
    name: ${{ matrix.os }} / ${{ matrix.pyversion }}
    runs-on: ${{ matrix.image }}
    defaults:
      run:
        shell: bash
    env:
      UV_LOCKED: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync

      - name: Lint
        run: |
          uv run flake8
          uv run ruff check

      - name: Python type checking
        run: uv run mypy

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'Windows'

      - name: Run tests
        run: uv run pytest --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.os == 'Ubuntu' && matrix.pyversion == '3.13'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
